services:
  hauspet_api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      hauspet_test_db:
        condition: service_healthy
      hauspet_redis:
        condition: service_healthy
      hauspet_audit_db:
        condition: service_healthy
    container_name: hauspet_api_test
    working_dir: /app
    environment:
      - NODE_ENV=test
      - PORT=3000
      - PERSISTENCE_TYPE=postgres
      - DB_HOST=hauspet_test_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=hauspet_test_db
      - DB_PORT=5432
      - REDIS_HOST=hauspet_redis
      - REDIS_PORT=6379
      - AUDIT_DB_URI=mongodb://audit_user:audit_pass@hauspet_audit_db:27017/audit_log_db?authSource=admin
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
    command: sh -c "npm install --silent && ./node_modules/.bin/ts-node src/index.ts"
    restart: unless-stopped
    networks:
      - hauspet-test-network

  hauspet_test_db:
    image: postgres:14-alpine
    container_name: hauspet_test_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hauspet_test_db
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres_test:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d hauspet_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hauspet-test-network

  hauspet_audit_db:
    image: mongo:6.0
    container_name: hauspet_audit_db_test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=audit_user
      - MONGO_INITDB_ROOT_PASSWORD=audit_pass
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo_test:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hauspet-test-network

  hauspet_redis:
    image: redis:7-alpine
    container_name: hauspet_redis_test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hauspet-test-network

networks:
  hauspet-test-network:
    driver: bridge
