version: "3.9"

services:
  apicat_api:
    image: node:22-alpine
    container_name: apicat_api
    depends_on:
      apicat_db:
        condition: service_healthy
      apicat_redis:
        condition: service_healthy
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PERSISTENCE_TYPE=postgres
      - DB_HOST=apicat_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=apicat_db
      - DB_PORT=5432
      - REDIS_HOST=apicat_redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped

  apicat_worker:
    image: node:22-alpine
    container_name: apicat_worker
    depends_on:
      apicat_db:
        condition: service_healthy
      apicat_redis:
        condition: service_healthy
    working_dir: /app
    environment:
      - NODE_ENV=development
      - DB_HOST=apicat_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=apicat_db
      - DB_PORT=5432
      - REDIS_HOST=apicat_redis
      - REDIS_PORT=6379
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run start:worker"
    restart: unless-stopped

  apicat_db:
    image: postgres:14-alpine
    container_name: apicat_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=apicat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d apicat_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  apicat_redis:
    image: redis:7-alpine
    container_name: apicat_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  node_modules:
  postgres_data:
