version: "3.9"

services:
  api_cat_nodejs:
    depends_on:
      - db
    image: node:22-alpine
    container_name: api_cat_nodejs
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PERSISTENCE_TYPE=postgres
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=apicat_db
      - DB_PORT=5432
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=apicat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  node_modules:
  postgres_data:
